## Analyse de données avec Numpy

### Objectif

In [121]:
import numpy as np
world_alcohol = np.genfromtxt("world-alcohol.csv", delimiter = ",", dtype = 'U75', skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Effectuer des comparaison

In [8]:
vector = np.array([5,10,15,20])

In [9]:
vector == 10

array([False,  True, False, False])

In [11]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [12]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

- Extraire la 3ème colonne de world_alcohol et comparer la au pays "Canada". Assigner le résultat à la variable countries_canada.
- Extraire la première colonne de world_alcohol et comparer la à la chaine de caractère "1984". Assigner le résultat à la variable years_1984.

In [29]:
 countries_canada = (world_alcohol[:,2] == "Canada")

In [30]:
countries_canada

array([False, False, False, ..., False, False, False])

In [31]:
 years_1984 = (world_alcohol[:,0] == "1984")

In [32]:
years_1984

array([False, False, False, ..., False, False, False])

### Sélectionner des éléments

In [34]:
vector = np.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[10]


In [35]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25,:])

[[20 25 30]]


- Comparer la 3e colonne de wolrd_alcohol à la chaine de caractère 'Algeria'.
- Assigner le résultat à la variable country_is_algeria.
- Selectionner seulement les lignes de world_alcohol pour lesquelles country_is_algeria vaut True
- Assigner le résultat à la variable country_algeria.
- Afficher les résultats.
- Faire le même travail pour récupérer toutes les lignes correspondantes à l'année "1984".Assigner le résultat à la variable yeards_1984.

In [42]:
country_is_algeria = (world_alcohol[:,2] == "Algeria")

In [47]:
country_algeria = world_alcohol[country_is_algeria]
country_algeria

array([['1984', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1987', 'Africa', 'Algeria', 'Beer', '0.17'],
       ['1987', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1984', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Beer', '0.16'],
       ['1989', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1989', 'Africa', 'Algeria', 'Wine', '0.23'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1984', 'Africa', 'Algeria', 'Wine', '0.12'],
       ['1985', 'Africa', 'Algeria', 'Beer', '0.19'],
       ['1985', 'Africa', 'Algeria', 'Other', '0'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1985', 'Africa', 'Algeria', 'Wine', '0.11'],
       ['1986', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Other', '0'],
       ['1987', 'Africa', 'Algeria', 'Other', '0'],
       ['1984', 'Africa', 'Algeria', 'Beer', '0.2'],
       ['1985', 'Africa', 'A

In [48]:
yeards_is_1984 = (world_alcohol[:,0] == "1984")
yeards_1984 = world_alcohol[yeards_is_1984]
yeards_1984

array([['1984', 'Africa', 'Nigeria', 'Other', '6.1'],
       ['1984', 'Eastern Mediterranean', 'Afghanistan', 'Other', '0'],
       ['1984', 'Americas', 'Costa Rica', 'Wine', '0.06'],
       ...,
       ['1984', 'Europe', 'Latvia', 'Spirits', '7.5'],
       ['1984', 'Africa', 'Angola', 'Wine', '0.57'],
       ['1984', 'Africa', 'Central African Republic', 'Wine', '0.46']],
      dtype='<U75')

### Effectuer des comparaisons avec plusieurs conditions

In [49]:
vector

array([ 5, 10, 15, 20])

In [52]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[ True  True False False]


In [53]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


- Selectionner les lignes dont le pays est 'Algeria' et l'année '1986':
    - Créer cette double comparaison et assigner le résultat à la variable is_algeria_and_1986.
    - Utiliser is_algeria_and_1986 pour sélectionner les lignes correspondantes dans le tableau wold_alcohol.
    - Assigner le résultat à la variable rows_with_algeria_and_1986.
    - Afficher le résultat.

In [54]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1986")

In [55]:
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]

In [56]:
print (rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


### Remplacer des valeurs dans un tableau Numpy

In [57]:
vector

array([ 5, 10, 15, 20])

In [58]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [59]:
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [60]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
second_column_25 = matrix[:,1]== 25
print(second_column_25)

[False  True False]


In [62]:
matrix[second_column_25,1] =10
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


- Creer un tableau numpy world_alcohol_2 égal world_alcohol pour le dupliquer sous un autre nom.
- Remplacer toutes les années "1986" de la première colonne de world_alcohol_2 par "2018"
- Remplacer tous les alcools "Wine" de la 4e colonne de world_alcohol_2 par "Beer".

In [63]:
world_alcohol_2 = world_alcohol

In [64]:
world_alcohol_2_1986 = world_alcohol_2[:,0] == '1986'

In [65]:
world_alcohol_2[world_alcohol_2_1986,0]= '2018'
print(world_alcohol_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


In [67]:
world_alcohol_2_wine = world_alcohol_2[:,3] == 'Wine'

In [68]:
world_alcohol_2[world_alcohol_2_wine,3]= 'Beer'
print(world_alcohol_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


### Remplacer les chaines de caractères vides

- Comparer tous les éléments de la 5e colonne de world_alcohol avec la chaine de caractères vide c-a-d ''. Assigner le résultat à la variable is_value_empty.
- Selectionner toutes les valeurs de la 5e colonnes de world_alcohol pour lesquels is_value_empty est égal à True et enfin les remplacer par la chainde caractère '0'.

In [69]:
is_value_empty = world_alcohol[:,4] == ''

In [70]:
world_alcohol[is_value_empty,4] = '0'

In [71]:
world_alcohol

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Convertir des types de données 

- Extraire la 5e colonne de worl_alcohol et assigner le résultat à la variable alcohol_consumption.
- Utiliser la méthode astype() pour convertir alcohol_consumption en décimal (float).

In [72]:
alcohol_consumption = world_alcohol[:,4]

In [73]:
alcohol_consumption = alcohol_consumption.astype(float)

In [74]:
alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

### Realisation des calculs mathématiques avec Numpy

In [76]:
vector = np.array([5,10,15,20])

In [77]:
vector.sum()

50

In [78]:
vector.mean()

12.5

In [79]:
vector.max()

20

In [81]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [82]:
matrix.sum(axis=1)

array([ 30,  75, 120])

matrix.sum(axis=0)

In [83]:
matrix.sum(axis=0)

array([60, 75, 90])

- Utiliser la méthode sum() pour calculer la somme des valeurs de alcohol_consumption. Assigner le résultat à la variable total_alcohol.
- Utiliser la méthode mean() pour calculer la moyenne des valeurs de alcohol_consumption.Assigner le résultat à la variable averag_alcohol.
- Afficher les résultats.

In [85]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()

In [86]:
print (total_alcohol)
print (average_alcohol)

3908.96
1.2001719373656738


### Calculer la consommation total annuelle par habitant pour un pays donné

In [87]:
print(world_alcohol[world_alcohol[:,2]== 'Canada'])

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Beer' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Beer' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['2018' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Beer' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '0']
 ['1985' 'Americas' 'Canada' 'Beer' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Beer' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '0']]


- Créer une matrice qu'on nommera canada_1986 qui contient toutes les lignes de world_alcohol correspondant à l'année '1986' et au pays 'Canada'.
- Extraire la 5e colonne de canada_1986, remplacer toute chaine de caractère vide ('') par '0' et convertir la colonne en décimal(float). Assigner le résultat à la variable canda_alcohol.
- Calculer ma somme canada_alcohol. Assigner le résultat à la variable total_canadian_drinking.
- Afficher le résultat.

In [136]:
canada_1986 = world_alcohol[(world_alcohol[:,2]== 'Canada') & (world_alcohol[:,0]== '1986')]

In [137]:
canada_1986[canada_1986[:,4] == '',4]= '0'

In [138]:
canada_alcohol=canada_1986[:,4]

In [139]:
canada_alcohol

array(['0', '3.11', '4.87', '1.33'], dtype='<U75')

In [140]:
canada_alcohol = canada_alcohol.astype(float)

In [141]:
total_canadian_drinking = canada_alcohol.sum()

In [142]:
total_canadian_drinking

9.31

### Calculer la consommation pour chaque pays

- Tout d'abord, on crée un dictionnaire vide qui va contenir tous les pays et leurs consommatoins d'alcool associées, on le nommera totals.
- Sélectionner ensuite le lignes de world-alcohol corrspondant à l'année donnée, disons 1989. Assigner le résultat à la variable year.
- Selectionner dans une liste qu'on nommera countries tous les pays.
- Parcourir tous les pays de la liste à l'aide d'une boucle.Pour chaque pays :
    - Selectionner les lignes de year correspondant à ce pays.
    - Assigner le résultat à la variable country_consumption.
    - Extraire la 5e colonne de country_consumption.
    - Remplacer toute chaine de caractère vide dans cette colonne par 0.
    - Convertir la colonne en décimal (float).
    - Calculer la somme de la colonne.
    - Ajouter la somme au dictionnaire totals, avec comme clé le nom du pays et en valeur cette somme.
- Afficher le dictionnaire totals.

In [143]:
import numpy as np
world_alcohol = np.genfromtxt("world-alcohol.csv", delimiter = ",", dtype = 'U75', skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [154]:
totals = {} 

In [155]:
year = world_alcohol[world_alcohol[:,0] == '1989',:]

In [163]:
countries = world_alcohol[:,2]

In [164]:
countries

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [172]:
for country in countries :
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = '0'
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()


In [173]:
totals

{'Viet Nam': 0.16,
 'Uruguay': 7.4399999999999995,
 "Cte d'Ivoire": 2.2,
 'Colombia': 6.960000000000001,
 'Saint Kitts and Nevis': 4.65,
 'Guatemala': 2.47,
 'Mauritius': 3.54,
 'Angola': 2.28,
 'Antigua and Barbuda': 4.69,
 'Nigeria': 6.74,
 'Botswana': 4.63,
 "Lao People's Democratic Republic": 5.95,
 'Afghanistan': 0.0,
 'Guinea-Bissau': 2.67,
 'Costa Rica': 5.3999999999999995,
 'Seychelles': 3.3000000000000003,
 'Norway': 5.08,
 'Kenya': 2.82,
 'Myanmar': 0.16,
 'Romania': 8.41,
 'Turkey': 0.72,
 'Comoros': 0.10999999999999999,
 'Tunisia': 0.95,
 'United Kingdom of Great Britain and Northern Ireland': 9.99,
 'Bahrain': 4.89,
 'Italy': 10.899999999999999,
 'Sierra Leone': 4.380000000000001,
 'Micronesia (Federated States of)': 0.0,
 'Mauritania': 0.02,
 'Russian Federation': 5.35,
 'Egypt': 0.42000000000000004,
 'Sweden': 7.47,
 'Qatar': 1.4500000000000002,
 'Burkina Faso': 3.99,
 'Austria': 13.9,
 'Czech Republic': 13.009999999999998,
 'Ukraine': 5.32,
 'China': 3.33,
 'Lithuania':

### Trouver le pays qui consomme le plus d'alcool

- Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
- Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
- Parcourir chaque pays du dictionnaire totals :
    - Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable et assigner la clé correspondante (nom du pays) à la variable highest_key.
- Afficher le pays qui consomme le plus d'alcool ( variable highest_key)

In [184]:
highest_value = 0
highest_key = 'None'

In [188]:
for country in totals :
    if totals[country] > highest_value :
        highest_value = totals[country]
        highest_key = country
            

In [189]:
print (highest_key)

Hungary
